server:
  applicationConnectors:
    - type: http
      port: 8008
      maxRequestHeaderSize: 16KiB
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    appenders:
      - type: file
        currentLogFilename: logs/requests.log
        archive: false